# Generated by Django 3.2.8 on 2021-10-10 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uhg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateTimeField(auto_now_add=True)),
                ('hiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to=settings.AUTH_USER_MODEL)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to='uhg.trail')),
            ],
        ),
    ]
